name: Cypress Tests

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (with retry)
        uses: nick-fields/retry@v2 # Action para reexecução
        with:
          timeout_minutes: 5 # Tempo limite para todas as tentativas
          max_attempts: 2     # Número máximo de tentativas (incluindo a primeira)
          command: npx cypress run --browser chrome 

      - name: Store screenshots (on failure)
        if: failure() 
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Store videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos