name: Cypress Tests

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome

      - name: Merge Mochawesome reports
        if: always() # Executa mesmo se os testes falharem
        run: |
          npx mochawesome-merge cypress/reports/mochawesome/.jsons/*.json > mochawesome.json
          npx marge mochawesome.json

      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: mochawesome-report/mochawesome.html

      - name: Store screenshots (on failure)
        if: always() 
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Store videos (on failure)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos